import {useState,type FormEvent} from 'react';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {ShieldCheck,Eye,EyeOff,WashingMachine} from 'lucide-react';
import {useApp} from '../context';
import {post,message} from '../api';
import type {User,Role} from '../types';
import {Field,ErrorBox} from '../components/UI';
export function AuthPanel({join=false,onSuccess,customerOnly=false}:{join?:boolean;onSuccess?:()=>void;customerOnly?:boolean}){
 const {catalog,setUser,demo,switchDemo}=useApp(),[register,setRegister]=useState(join),[busy,setBusy]=useState(false),[error,setError]=useState(''),[visible,setVisible]=useState(false),[role,setRole]=useState<Role>(join&&!customerOnly?'provider':'customer');
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');try{const data=await post<{user:User}>(register?'/auth/register':'/auth/login',register?{name:form.get('name'),email:form.get('email'),phone:form.get('phone'),password:form.get('password'),area:form.get('area'),role}:{identifier:form.get('identifier'),password:form.get('password')});if(customerOnly&&data.user.role!=='customer'){setUser(data.user);throw new Error('Sign in with a customer account to make this booking.');}setUser(data.user);onSuccess?.();}catch(err){setError(message(err));}finally{setBusy(false);}};
 return <><div className="segmented"><button className={!register?'active':''} onClick={()=>setRegister(false)}>Sign in</button><button className={register?'active':''} onClick={()=>setRegister(true)}>Create account</button></div><ErrorBox text={error}/><form onSubmit={e=>void submit(e)} className="form-stack">{register?<><Field label="Your name"><input name="name" autoComplete="name" minLength={2} maxLength={80} required placeholder="Jane Wanjiku"/></Field><div className="form-grid"><Field label="Email"><input name="email" autoComplete="email" type="email" required/></Field><Field label="Phone number"><input name="phone" autoComplete="tel" type="tel" required placeholder="07XX XXX XXX"/></Field></div>{!customerOnly&&<Field label="I want to"><select value={role} onChange={e=>setRole(e.target.value as Role)}><option value="customer">Book a service</option><option value="provider">Offer laundry or cleaning</option><option value="rider">Handle pickup and delivery</option></select></Field>}<Field label="Your Maseno area"><select name="area" required>{catalog?.areas.map(a=><option key={a}>{a}</option>)}</select></Field></>:<Field label="Email or phone number"><input name="identifier" autoComplete="username" required placeholder="Email or 07XX XXX XXX"/></Field>}<Field label="Password" hint={register?'At least 10 characters.':'Use the password you registered with.'}><div className="password-field"><input name="password" type={visible?'text':'password'} autoComplete={register?'new-password':'current-password'} minLength={register?10:1} maxLength={128} required/><button type="button" className="icon-btn" onClick={()=>setVisible(!visible)} aria-label={visible?'Hide password':'Show password'}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></Field>{register&&<label className="check"><input type="checkbox" required/><span>I agree to the <Link to="/policies">service terms and privacy policy</Link>.</span></label>}<button className="btn full" disabled={busy}>{busy?'Please wait…':register?'Create account':'Sign in'}</button></form>{demo&&<div className="demo-login"><span>Just exploring?</span><button className="text-link" onClick={()=>void switchDemo(customerOnly?'customer':role).then(()=>onSuccess?.()).catch(e=>setError(message(e)))}>Try the {customerOnly?'customer':role==='provider'?'Mama Fua':role} demo</button></div>}</>;
}
export default function Auth({join=false}:{join?:boolean}){const navigate=useNavigate(),[params]=useSearchParams(),{user}=useApp();const rawReturn=params.get('return')||'/dashboard',returnTo=rawReturn.startsWith('/')&&!rawReturn.startsWith('//')?rawReturn:'/dashboard';return <div className="container section auth-layout"><div className="auth-story"><span className="eyebrow">{join?'Grow with your neighbourhood':'Welcome back to a lighter day'}</span><h1>{join?'Your skills.\nYour local business.':'Fresh starts\nhappen here.'}</h1><p>{join?'Offer laundry, home washing or cleaning around Maseno. Set your service areas, complete verification and receive requests when you’re available.':'Sign in to follow your laundry, save your favourite provider and make the next booking even easier.'}</p><img src={join?'/images/mama-portrait.webp':'/images/folded-clothes.webp'} alt={join?'Kenyan Mama Fua at work':'Clean folded laundry'} width="600" height="400"/><span className="row gap"><ShieldCheck size={18}/> Local care, built on trust.</span></div><div className="panel auth-panel"><WashingMachine size={30}/><h2>{join?'Become a partner':'Your LaundryApp account'}</h2>{user?<><p>You’re signed in as {user.name}.</p><Link className="btn" to="/dashboard">Open dashboard</Link></>:<AuthPanel join={join} onSuccess={()=>navigate(returnTo)}/>}</div></div>;}
