import {useEffect,useState} from 'react';
import {Search,SlidersHorizontal} from 'lucide-react';
import {useSearchParams} from 'react-router-dom';
import {useApp} from '../context';
import {api,message} from '../api';
import type {Provider} from '../types';
import ProviderCard from '../components/ProviderCard';
import {PageHead,Field,Spinner,ErrorBox,Empty} from '../components/UI';
export default function Providers(){const {catalog,user}=useApp(),[params,setParams]=useSearchParams(),[providers,setProviders]=useState<Provider[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[available,setAvailable]=useState(false);const area=params.get('area')||'',service=params.get('service')||'',type=params.get('type')||'',saved=params.get('saved')==='true';
 useEffect(()=>{const controller=new AbortController();setLoading(true);api<{providers:Provider[]}>(`/providers?${params}`,{signal:controller.signal}).then(d=>{setProviders(d.providers);setError('');}).catch(e=>{if(e.name!=='AbortError')setError(message(e));}).finally(()=>setLoading(false));return()=>controller.abort();},[params.toString()]);
 const change=(key:string,value:string)=>{const p=new URLSearchParams(params);if(value)p.set(key,value);else p.delete(key);setParams(p);};const filtered=providers.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())&&(!available||p.online)&&(!saved||user?.favourites.includes(p.id)));
 return <div className="container section"><PageHead eyebrow="Good people. Good care." title="Find your local helping hand." description="Mama Fua, laundry businesses and cleaning teams serving Maseno."/><div className="filter-bar"><label className="search-input"><Search size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search providers" aria-label="Search providers"/></label><Field label="Your area"><select value={area} onChange={e=>change('area',e.target.value)}><option value="">All Maseno areas</option>{catalog?.areas.map(a=><option key={a}>{a}</option>)}</select></Field><Field label="Service"><select value={service} onChange={e=>change('service',e.target.value)}><option value="">All services</option>{catalog?.services.filter(s=>s.active).map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></Field><Field label="Provider type"><select value={type} onChange={e=>change('type',e.target.value)}><option value="">All providers</option><option value="individual">Mama Fua</option><option value="laundry_business">Laundry business</option><option value="cleaning_company">Cleaning company</option></select></Field></div><div className="row between filter-meta"><span className="row gap"><SlidersHorizontal size={17}/>{filtered.length} providers</span><div className="row gap"><label className="check"><input type="checkbox" checked={available} onChange={e=>setAvailable(e.target.checked)}/> Available now</label>{user?.role==='customer'&&<label className="check"><input type="checkbox" checked={saved} onChange={e=>change('saved',e.target.checked?'true':'')}/> My favourites</label>}</div></div><ErrorBox text={error}/>{loading?<Spinner/>:filtered.length?<div className="provider-grid">{filtered.map(p=><ProviderCard provider={p} key={p.id}/>)}</div>:<Empty title="No providers match yet." description="Try another area or service. You can still post a request for an available provider." to="/book?service=custom_job" label="Post a job"/>}</div>;
}
