import {useEffect,useState} from 'react';
import {useParams,Link} from 'react-router-dom';
import {MapPin,Check,UserRound} from 'lucide-react';
import {api,providerTypes,fulfilmentLabels,message,date} from '../api';
import {useApp} from '../context';
import type {Provider,Review} from '../types';
import {Spinner,ErrorBox,Rating,Verified,Icon} from '../components/UI';
export default function ProviderProfile(){const {id}=useParams(),{catalog,demo}=useApp(),[data,setData]=useState<{provider:Provider;reviews:Review[]}|null>(null),[error,setError]=useState('');useEffect(()=>{api<{provider:Provider;reviews:Review[]}>(`/providers/${id}`).then(setData).catch(e=>setError(message(e)));},[id]);if(error)return <div className="container section"><ErrorBox text={error}/></div>;if(!data)return <Spinner/>;const p=data.provider;
 return <div className="container section"><Link className="text-link" to="/providers">All providers</Link><div className="profile-hero panel">{p.avatar?<img src={p.avatar} className="profile-photo" alt={p.name} width="160" height="160"/>:<div className="profile-photo avatar"><UserRound size={55}/></div>}<div><div className="eyebrow">{providerTypes[p.type]}</div><h1>{p.name}</h1><div className="row gap"><Verified/><Rating rating={p.rating} count={p.reviewCount}/><span className="badge">{p.online?'Available for requests':'Currently offline'}</span></div><p className="row gap"><MapPin size={16}/>{p.area} · Serves within {p.radius} km</p>{demo&&p.demo&&<small className="muted">Sample provider profile in preview mode</small>}</div><Link className={`btn ${p.online?'':'disabled'}`} aria-disabled={!p.online} to={p.online?`/book?provider=${p.id}&service=${p.categories[0]}`:'#'}>Book with {p.name}</Link></div><div className="profile-columns"><div><section className="panel"><h2>A little about your provider</h2><p>{p.bio}</p><h3>How I can help</h3><div className="tag-list">{p.fulfilments.map(f=><span key={f}><Check size={15}/>{fulfilmentLabels[f]}</span>)}</div><h3>Services</h3><div className="profile-services">{p.categories.map(s=>{const service=catalog?.services.find(v=>v.id===s);return <Link to={`/book?provider=${p.id}&service=${s}`} key={s}><Icon name={service?.icon||'washer'}/><span>{service?.name}</span></Link>;})}</div></section><section className="panel"><h2>Customer reviews</h2>{data.reviews.length?data.reviews.map(r=><article className="review" key={r.id}><div className="row between"><strong>{r.customerName}</strong><Rating rating={r.rating}/></div><p>{r.text}</p><small className="muted">Verified completed booking · {date(r.createdAt)}</small></article>):<p className="muted">Reviews appear here after customers complete a booking.</p>}</section></div><aside className="panel"><h2>Close to home</h2><p>Service areas</p><div className="area-list">{p.areas.map(a=><span key={a}><MapPin size={14}/>{a}</span>)}</div><div className="info-callout compact"><p>Your provider’s phone and WhatsApp contact become available after your booking is accepted.</p></div></aside></div></div>;
}
