import {useEffect,useRef,useState} from 'react';
import Motion from './Motion';
import {Link,NavLink,Outlet,useNavigate,useLocation} from 'react-router-dom';
import {WashingMachine,MapPin,Bell,Menu,X,Heart,ShieldCheck,Phone,HelpCircle,LogOut,LayoutDashboard,CalendarDays,Users} from 'lucide-react';
import {useApp} from '../context';
import type {Role} from '../types';
import {message} from '../api';
import {Modal} from './UI';
export default function Layout(){
 const {user,demo,logout,notifications,switchDemo,notify,toast,payment,online}=useApp(),navigate=useNavigate(),location=useLocation(),[open,setOpen]=useState(false),[demoOpen,setDemoOpen]=useState(false),[scrolled,setScrolled]=useState(false);
 useEffect(()=>{const update=()=>setScrolled(window.scrollY>24);update();window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update);},[]);
 useEffect(()=>{setOpen(false);},[location.pathname]);
 const headerRef=useRef<HTMLElement>(null),menuRef=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!open)return;const keyboard=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);menuRef.current?.focus();}};const outside=(e:PointerEvent)=>{if(!headerRef.current?.contains(e.target as Node))setOpen(false);};document.addEventListener('keydown',keyboard);document.addEventListener('pointerdown',outside);return()=>{document.removeEventListener('keydown',keyboard);document.removeEventListener('pointerdown',outside);};},[open]);
 const change=async(role:Role)=>{try{await switchDemo(role);navigate('/dashboard');setDemoOpen(false);notify(`Exploring the ${role==='provider'?'Mama Fua':role} account`);}catch(e){notify(message(e));}};
 const close=()=>setOpen(false);
 return <><a href="#main" className="skip-link">Skip to content</a><div className="top-strip"><div className="container row between"><span><MapPin size={14}/> Made for Maseno. Right around your corner.</span>{demo?<button className="demo-launch" onClick={()=>setDemoOpen(true)} aria-label="Explore demo accounts"><LayoutDashboard size={17}/><span>Explore demo</span></button>:<Link to="/help">Need a hand? <HelpCircle size={14}/></Link>}</div></div><header ref={headerRef} className={`site-header ${scrolled?'is-scrolled':''}`}><div className="container header-inner"><Link className="brand" to="/" onClick={close}><span className="brand-icon"><WashingMachine size={24}/></span>Laundry<span>App</span><span className="brand-dot">.</span></Link><nav id="main-navigation" className={open?'nav-links open':'nav-links'} aria-label="Main navigation"><NavLink to="/services" onClick={close}><WashingMachine className="mobile-nav-icon" aria-hidden="true" size={20}/>Our services</NavLink><NavLink to="/providers" onClick={close}><Users className="mobile-nav-icon" aria-hidden="true" size={20}/>Find a Mama Fua</NavLink><NavLink to="/plans" onClick={close}><CalendarDays className="mobile-nav-icon" aria-hidden="true" size={20}/>Student plans</NavLink><NavLink to="/join" onClick={close}><Heart className="mobile-nav-icon" aria-hidden="true" size={20}/>Become a partner</NavLink><Link className="mobile-account" to={user?'/dashboard':'/login'} onClick={close}>{user?'My dashboard':'Sign in'}</Link></nav><div className="header-actions">{user?<><Link className="icon-btn notification-btn" to="/notifications" aria-label="Notifications"><Bell size={20}/>{notifications.some(n=>!n.read)&&<span className="notification-dot"/>}</Link></>:<Link className="sign-in" to="/login">Sign in</Link>}<Link className="btn small" to="/book">Book a service</Link><button ref={menuRef} aria-controls="main-navigation" className="icon-btn menu-toggle" onClick={()=>setOpen(!open)} aria-label={open?'Close menu':'Open menu'} aria-expanded={open}>{open?<X/>:<Menu/>}</button></div></div></header>
 {demo&&location.pathname!=='/'&&<div className="preview-bar">Preview mode · Sample accounts and bookings. {payment.demo?'Payments are simulated.':payment.available?'Swifta API calls are enabled.':'Online payments are being connected.'}</div>}
 <Motion/><main id="main">{!online&&<div className="connection-banner" role="status">You’re offline. Showing saved information from this tab. Reconnect to book, pay or update a job.</div>}<div className="route-surface" key={location.pathname}><Outlet/></div></main>
 <footer className="footer"><div className="container footer-grid"><div><Link className="brand" to="/"><span className="brand-icon"><WashingMachine size={24}/></span>Laundry<span>App</span>.</Link><p>Fresh clothes. Clean spaces.<br/>A little more time for you.</p><span className="local-mark"><MapPin size={16}/> Proudly made for Maseno</span></div><div><h4>A hand around home</h4><Link to="/book">Laundry pickup</Link><Link to="/book?fulfilment=at_home">Mama Fua at your place</Link><Link to="/book?service=house_cleaning">House cleaning</Link><Link to="/book?service=custom_job">Post a job</Link></div><div><h4>Your LaundryApp</h4><Link to="/dashboard">Bookings & receipts</Link><Link to="/plans">Student plans</Link><Link to="/join">Become a partner</Link><Link to="/help">Help & support</Link></div><div><h4>A little peace of mind</h4><span><ShieldCheck size={16}/> Verified service partners</span><span><Phone size={16}/> Contact after acceptance</span><span><Heart size={16}/> Local people, local care</span><Link to="/policies">Privacy & service terms</Link></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} LaundryApp · Maseno, Kenya</span><span>Payments powered by Swifta · M-Pesa</span></div></footer>
 {demo&&<>{demoOpen&&<Modal title="Explore demo accounts" close={()=>setDemoOpen(false)}><p className="muted">Try every side of the marketplace. Bookings stay in sync as you switch accounts. {payment.demo?'Payments are simulated.':payment.available?'Real Swifta requests are enabled.':'Online payments are being connected.'}</p><div className="demo-role-grid">{(['customer','provider','rider','admin'] as Role[]).map(role=><button className="btn secondary" key={role} onClick={()=>void change(role)}>{role==='provider'?'Mama Fua':role==='customer'?'Customer':role==='rider'?'Delivery rider':'Admin'}</button>)}</div>{user&&<button className="text-link demo-signout" onClick={()=>void logout().then(()=>{setDemoOpen(false);navigate('/');}).catch(e=>notify(message(e)))}><LogOut size={16}/>Sign out</button>}</Modal>}</>}
 {toast&&<div className="toast" role="status">{toast}<button onClick={()=>notify('')} aria-label="Dismiss notification"><X size={16}/></button></div>}
 </>;
}
