import {Link,useNavigate} from 'react-router-dom';
import {Heart,MapPin,UserRound,ArrowUpRight} from 'lucide-react';
import type {Provider,User} from '../types';
import {useApp} from '../context';
import {post,providerTypes,message} from '../api';
import {Rating,Verified} from './UI';
export default function ProviderCard({provider:p}:{provider:Provider}){
 const {user,setUser,notify,demo,catalog}=useApp(),navigate=useNavigate();
 const favourite=async()=>{if(!user){navigate('/login');return;}try{const d=await post<{user:User}>(`/favourites/${p.id}`);setUser(d.user);}catch(e){notify(message(e));}};
 return <article className="provider-card"><div className="provider-top">{p.avatar?<img src={p.avatar} alt={p.name} width="72" height="72" loading="lazy"/>:<div className="avatar"><UserRound/></div>}<div><div className="provider-kind">{providerTypes[p.type]}</div><Link className="provider-name" to={`/providers/${p.id}`}>{p.name}</Link><div className="row gap"><Rating rating={p.rating} count={p.reviewCount}/>{p.verified&&<Verified/>}</div></div>{(!user||user.role==='customer')&&<button className={`icon-btn favourite ${user?.favourites.includes(p.id)?'saved':''}`} onClick={()=>void favourite()} aria-pressed={!!user?.favourites.includes(p.id)} aria-label={`${user?.favourites.includes(p.id)?'Unsave':'Save'} ${p.name}`}><Heart size={20} fill={user?.favourites.includes(p.id)?'currentColor':'none'}/></button>}</div><p>{p.bio}</p><div className="provider-specialties">{p.categories.slice(0,2).map(id=>{const service=catalog?.services.find(s=>s.id===id);return service?<span key={id}>{service.name}</span>:null;})}</div><div className="provider-bottom"><span><MapPin size={15}/>{p.area}</span><span className={p.online?'available provider-availability':'muted provider-availability'}>{p.online?'Available':'Offline'}</span></div><div className="provider-rate"><span>{p.fulfilments.includes('at_home')?'Wash at home':p.fulfilments.includes('cleaning')?'House cleaning':'Laundry pickup'}</span><strong>{p.fulfilments.includes('at_home')?`from KSh ${catalog?.loads[0].price||0}`:p.fulfilments.includes('cleaning')?`from KSh ${catalog?.services.find(s=>s.id==='house_cleaning')?.price||0}`:`from KSh ${(catalog?.loads[0].price||0)+(catalog?.fees.pickup||0)+(catalog?.fees.delivery||0)}`}</strong></div><div className="row between provider-card-action"><Link className="text-link" to={`/providers/${p.id}`}>View profile <ArrowUpRight size={18}/></Link>{demo&&p.demo&&<small className="muted">Sample provider</small>}</div></article>;
}
