export type Role='customer'|'provider'|'rider'|'admin';
export type Fulfilment='pickup'|'at_home'|'cleaning'|'custom';
export interface Address {id:string;label:string;area:string;address:string}
export interface User {id:string;name:string;email:string;phone:string;role:Role;area:string;addresses:Address[];favourites:string[];demo?:boolean;approved?:boolean;suspended?:boolean;vehicle?:string}
export interface Service {id:string;name:string;description:string;price:number;kgPrice:number;itemPricing:boolean;itemExtra?:number;quickExtra?:number;active:boolean;fulfilments:Fulfilment[];duration:string;icon:string}
export interface Load {id:string;name:string;detail:string;price:number;weight:number}
export interface Plan {id:string;name:string;description:string;price:number;frequency:'weekly'|'biweekly'|'monthly';load:string;serviceId:string;bookings:number}
export interface Catalog {areas:string[];legacyAreas:string[];timeSlots:string[];fees:{pickup:number;delivery:number;express:number;depositPercent:number;commissionPercent:number};services:Service[];loads:Load[];items:{id:string;name:string;price:number}[];promos:{code:string;discount:number;active:boolean}[];plans:Plan[]}
export interface Provider {id:string;userId?:string;name:string;type:'individual'|'laundry_business'|'cleaning_company';bio:string;area:string;areas:string[];radius:number;categories:string[];fulfilments:Fulfilment[];rating:number;reviewCount:number;online:boolean;verified:boolean;verificationStatus:string;verificationNote?:string;avatar:string|null;verificationDocuments?:string[];demo?:boolean}
export interface BookingInput {serviceId:string;fulfilment:Fulfilment;pricingMode:'quick'|'item'|'kg'|'fixed';load:string;quantities:Record<string,number>;weight:number;itemCount:number;area:string;address:string;scheduledAt:string|null;timeSlot:'morning'|'afternoon'|'evening';notes:string;express:boolean;promo:string;paymentMode:'upfront'|'deposit'|'after';preferredProvider:string|null;recurrence:'none'|'weekly'|'biweekly'|'monthly';photos:string[];budget:number|null;customTask:string;idempotencyKey?:string;planId:string|null}
export interface Quote {items:{name:string;quantity:number;price:number}[];basePrice:number;pickupFee:number;deliveryFee:number;expressFee:number;discount:number;total:number;dueNow:number;serviceName:string;planName?:string}
export interface Review {id:string;orderId:string;providerId:string;customerName:string;rating:number;text:string;createdAt:string;hidden:boolean}
export interface Payment {id:string;orderId:string;customerName:string;amount:number;status:string;receipt:string|null;adapter:string;createdAt:string;message?:string}
export interface Order extends BookingInput {commissionPercent?:number;transportLegs?:{riderId?:string|null;providerId?:string;leg:string;fee:number;at:string}[];id:string;bagTag:string;customerId:string;customerName:string;customerPhone:string;providerId:string|null;provider?:Provider|null;providerPhone?:string;riderId:string|null;riderName?:string;riderPhone?:string;status:string;quote:Quote;paidAmount:number;paymentStatus:string;refundAmount:number;refundStatus:string|null;refundReference?:string;returnRequired?:boolean;returnStatus?:string;cancellationReason?:string;createdAt:string;updatedAt:string;startPin?:string;eta:string;locationShare?:string;events:{status:string;at:string;note:string}[];review?:Review|null;payments:Payment[]}
export interface Notification {id:string;title:string;message:string;orderId:string|null;read:boolean;createdAt:string}
export interface Recurring {id:string;frequency:string;nextAt:string;active:boolean;template:BookingInput;error?:string}
export interface Issue {id:string;userName:string;role:string;orderId:string|null;category:string;message:string;status:string;reply:string;createdAt:string}
export interface Earnings {entries:{id:string;entryId?:string;viewable?:boolean;bagTag:string;date:string;gross:number;net:number;received:boolean}[];total:number;paid:number;completed:number;commission:number}
export interface AdminData {users:User[];providers:Provider[];payments:Payment[];reviews:Review[];issues:Issue[];metrics:{total:number;active:number;completedToday:number;revenue:number;refunds:number};audit:{id:number;user_id:string;action:string;entity:string;created_at:string}[]}
export interface RequestJob {id:string;bagTag:string;serviceName:string;fulfilment:Fulfilment;area:string;scheduledAt:string|null;createdAt:string;quote:Quote;notes:string;customTask:string;budget:number|null;itemCount:number;weight:number;paymentMode:string}
export interface RiderJob {id:string;bagTag:string;serviceName:string;area:string;providerName:string;providerArea:string;status:string;fee:number;scheduledAt:string|null}
